# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(560, 457)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(20, 70, 519, 306))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.le_ammonia_concentration = QtWidgets.QLineEdit(self.widget)
        self.le_ammonia_concentration.setObjectName("le_ammonia_concentration")
        self.verticalLayout_2.addWidget(self.le_ammonia_concentration)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.le_toluene_concentration = QtWidgets.QLineEdit(self.widget)
        self.le_toluene_concentration.setObjectName("le_toluene_concentration")
        self.verticalLayout_3.addWidget(self.le_toluene_concentration)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.le_propanol_concentration = QtWidgets.QLineEdit(self.widget)
        self.le_propanol_concentration.setObjectName("le_propanol_concentration")
        self.verticalLayout_4.addWidget(self.le_propanol_concentration)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.btn_start_collect = QtWidgets.QPushButton(self.widget)
        self.btn_start_collect.setObjectName("btn_start_collect")
        self.horizontalLayout.addWidget(self.btn_start_collect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.le_file_input = QtWidgets.QLineEdit(self.widget)
        self.le_file_input.setObjectName("le_file_input")
        self.horizontalLayout_2.addWidget(self.le_file_input)
        self.btn_choose_file = QtWidgets.QPushButton(self.widget)
        self.btn_choose_file.setObjectName("btn_choose_file")
        self.horizontalLayout_2.addWidget(self.btn_choose_file)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.te_result = QtWidgets.QTextEdit(self.widget)
        self.te_result.setObjectName("te_result")
        self.verticalLayout.addWidget(self.te_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "氨气浓度"))
        self.label_2.setText(_translate("Form", "甲苯浓度"))
        self.label_3.setText(_translate("Form", "丙醇浓度"))
        self.btn_start_collect.setText(_translate("Form", "开始采集"))
        self.label_4.setText(_translate("Form", "文件名"))
        self.btn_choose_file.setText(_translate("Form", "选择文件"))
